export const LOAD_COUNTRY_BY_NAME = 'LOAD_COUNTRY_BY_NAME';
export const LOAD_COUNTRY_BY_FULL_NAME = 'LOAD_COUNTRY_BY_FULL_NAME';
export const LOAD_COUNTRY_BY_CODE = 'LOAD_COUNTRY_BY_CODE';
export const LOAD_COUNTRY_BY_CURRENCY = 'LOAD_COUNTRY_BY_CURRENCY';

export const INPUT_COUNTRY_NAME = 'INPUT_COUNTRY_NAME';

export const CHANGE_PAGES = 'CHANGE_PAGES';
export const CHANGE_COUNTRY_CHECKED = 'CHANGE_COUNTRY_CHECKED';
export const CHANGE_LANGUAGES_STORAGE = 'CHANGE_LANGUAGES_STORAGE';

export const GET_ENTITIES_IN_STORAGE = 'GET_ENTITIES_IN_STORAGE';


export const START = '_START';
export const SUCCESS = '_SUCCESS';
export const FAIL = '_FAIL';

export const HOST = 'https://restcountries.eu/rest/v2/';